"""常用搭配模块 — 显示词组搭配

Provides common collocations and phrases for English words.
Uses a curated database of ~250 high-frequency words with their
typical verb-noun, adjective-noun, and other common combinations.
"""

from typing import Dict, List, Optional


# ── 常用搭配数据库 ──
# Each entry: word → list of collocations / phrases
_COLLOCATIONS_DB: Dict[str, List[str]] = {
    # ── 动词 ──
    "make": ["make a decision", "make progress", "make money", "make a mistake",
             "make sense", "make an effort", "make a difference", "make friends",
             "make sure", "make up one's mind"],
    "take": ["take a break", "take a chance", "take advantage of", "take care of",
             "take into account", "take notes", "take place", "take part in",
             "take responsibility", "take action"],
    "give": ["give advice", "give birth to", "give way", "give rise to",
             "give permission", "give priority to", "give a speech",
             "give someone a hand", "give up hope", "give feedback"],
    "have": ["have a look", "have an effect on", "have difficulty", "have access to",
             "have the right to", "have no choice", "have a good time",
             "have something in common", "have a point", "have experience"],
    "get": ["get rid of", "get along with", "get used to", "get in touch with",
            "get the hang of", "get on one's nerves", "get carried away",
            "get down to business", "get the picture", "get a grip"],
    "do": ["do one's best", "do business", "do harm", "do justice to",
           "do research", "do a favor", "do the dishes", "do homework",
           "do damage", "do wonders"],
    "put": ["put forward", "put off", "put up with", "put into practice",
            "put pressure on", "put an end to", "put emphasis on",
            "put in charge of", "put to use", "put aside"],
    "break": ["break the ice", "break the news", "break a promise", "break even",
              "break the rules", "break new ground", "break into tears",
              "break free", "break down barriers", "break a habit"],
    "keep": ["keep in mind", "keep track of", "keep up with", "keep an eye on",
             "keep in touch", "keep calm", "keep a secret", "keep pace with",
             "keep one's word", "keep balance"],
    "come": ["come across", "come up with", "come to terms with", "come into being",
             "come to a conclusion", "come in handy", "come true",
             "come to an end", "come to light", "come into play"],
    "turn": ["turn out", "turn down", "turn up", "turn into", "turn over",
             "turn a blind eye", "turn the tables", "turn to someone for help",
             "turn a corner", "turn one's back on"],
    "run": ["run out of", "run into", "run the risk of", "run a business",
            "run a marathon", "run short of", "run counter to",
            "run wild", "run up against", "run deep"],
    "set": ["set an example", "set foot in", "set the pace", "set fire to",
            "set one's mind to", "set the record straight", "set free",
            "set up a business", "set a goal", "set apart"],
    "hold": ["hold on", "hold back", "hold one's breath", "hold true",
             "hold the line", "hold a meeting", "hold an opinion",
             "hold responsible", "hold the key", "hold in high regard"],
    "look": ["look forward to", "look after", "look into", "look up to",
             "look down on", "look out for", "look back on", "look for trouble",
             "look the other way", "look on the bright side"],
    "carry": ["carry out", "carry on", "carry weight", "carry the day",
              "carry a torch for", "carry forward", "carry through",
              "carry the burden", "carry over", "carry oneself"],
    "bring": ["bring about", "bring up", "bring to light", "bring into question",
              "bring to mind", "bring to an end", "bring forth",
              "bring under control", "bring pressure to bear", "bring together"],
    "call": ["call for", "call off", "call on", "call into question",
             "call the shots", "call attention to", "call it a day",
             "call a meeting", "call names", "call forth"],
    "go": ["go through", "go ahead", "go without saying", "go hand in hand",
           "go wrong", "go through with", "go to great lengths",
           "go out of one's way", "go back on", "go over"],
    "work": ["work out", "work on", "work hard", "work together",
             "work overtime", "work wonders", "work one's way up",
             "work toward a goal", "work in progress", "work against time"],
    "play": ["play a role in", "play a part in", "play it safe", "play by ear",
             "play fair", "play a trick on", "play with fire",
             "play the field", "play down", "play up"],
    "find": ["find out", "find fault with", "find one's way", "find a solution",
             "find comfort in", "find oneself", "find a middle ground",
             "find common ground", "find it hard to", "find expression in"],
    "think": ["think about", "think of", "think highly of", "think twice",
              "think outside the box", "think ahead", "think better of",
              "think nothing of", "think through", "think aloud"],
    "give": ["give up", "give in", "give away", "give off", "give birth to",
             "give way to", "give rise to", "give priority to",
             "give someone the benefit of the doubt", "give credit to"],
    "show": ["show up", "show off", "show interest in", "show respect for",
             "show signs of", "show promise", "show the way",
             "show one's true colors", "show mercy", "show concern"],
    "know": ["know by heart", "know the ropes", "know for a fact",
             "know the difference", "know right from wrong",
             "know inside out", "know what's what", "know better than to",
             "know the score", "know no bounds"],
    "tell": ["tell the truth", "tell a lie", "tell the difference",
             "tell a story", "tell the time", "tell someone off",
             "tell fortunes", "tell tales", "tell apart", "tell on someone"],
    "feel": ["feel like", "feel at home", "feel the pinch", "feel sorry for",
             "feel strongly about", "feel one's way", "feel the heat",
             "feel blue", "feel at ease", "feel obligated to"],
    "leave": ["leave behind", "leave out", "leave room for", "leave a mark on",
              "leave no stone unturned", "leave to one's own devices",
              "leave a message", "leave a lasting impression", "leave alone",
              "leave in the dark"],
    "move": ["move on", "move forward", "move up", "move heaven and earth",
             "move the goalposts", "move with the times", "move toward",
             "move to tears", "move mountains", "move in the right direction"],
    "stand": ["stand for", "stand out", "stand by", "stand up for",
              "stand a chance", "stand the test of time", "stand in the way",
              "stand firm", "stand to reason", "stand guard"],
    "pay": ["pay attention to", "pay a visit", "pay the price", "pay tribute to",
            "pay off", "pay the bill", "pay one's respects", "pay a compliment",
            "pay dividends", "pay through the nose"],
    "try": ["try one's best", "try on", "try out", "try and error",
            "try one's patience", "try one's hand at", "try hard",
            "try for", "try to resist", "try to avoid"],
    "lose": ["lose control of", "lose one's temper", "lose track of",
             "lose heart", "lose hope", "lose touch with",
             "lose one's way", "lose sight of", "lose weight",
             "lose faith in"],
    "use": ["use up", "make use of", "put to use", "come in useful",
            "use one's head", "use common sense", "use caution",
            "use discretion", "use force", "use as a pretext"],
    "help": ["help out", "help oneself to", "help someone with",
             "can't help but", "lend a helping hand", "help someone along",
             "help matters", "with the help of", "God help us",
             "so help me"],
    "ask": ["ask for", "ask a favor", "ask permission", "ask questions",
            "ask after someone", "ask around", "ask for trouble",
            "ask for help", "ask someone out", "ask the impossible"],
    "seem": ["seem to be", "seem like", "seem impossible", "seem likely",
             "seem strange", "seem odd", "seem familiar", "seem obvious",
             "seem reasonable", "seem unaware of"],
    "read": ["read between the lines", "read out loud", "read up on",
             "read one's mind", "read into", "read through",
             "read from cover to cover", "read about", "read in bed",
             "read aloud"],
    "write": ["write down", "write off", "write back", "write out",
              "write in", "write about", "write home about",
              "write a letter", "write a report", "write to someone"],
    "speak": ["speak up", "speak one's mind", "speak highly of",
              "speak volumes", "speak for itself", "speak on behalf of",
              "speak the truth", "speak in public", "speak from experience",
              "speak at length"],
    "learn": ["learn by heart", "learn a lesson", "learn the ropes",
              "learn from experience", "learn the hard way",
              "learn to live with", "learn by doing", "learn about",
              "learn to adapt", "learn one's limits"],
    "grow": ["grow up", "grow apart", "grow out of", "grow on someone",
             "grow accustomed to", "grow in popularity", "grow into",
             "grow impatient", "grow in confidence", "grow weary of"],
    "open": ["open up", "open the door to", "open fire", "open one's eyes",
             "open a can of worms", "open for business", "open one's mind",
             "open an account", "open negotiations", "open to suggestion"],
    "close": ["close down", "close in on", "close the gap", "close the deal",
              "close to home", "close one's eyes to", "close ranks",
              "close at hand", "close the door on", "close out"],
    "cut": ["cut back on", "cut down on", "cut corners", "cut off",
            "cut in", "cut to the chase", "cut no ice", "cut a deal",
            "cut the mustard", "cut short"],
    "pick": ["pick up", "pick out", "pick on", "pick up the phone",
             "pick someone's brain", "pick a fight", "pick up speed",
             "pick up the pieces", "pick holes in", "pick one's way"],
    "pull": ["pull off", "pull through", "pull together", "pull one's leg",
             "pull strings", "pull the plug", "pull the wool over",
             "pull rank", "pull away", "pull up stakes"],
    "push": ["push for", "push back", "push forward", "push one's luck",
             "push the envelope", "push around", "push ahead",
             "push the button", "push to the limit", "push aside"],
    "build": ["build up", "build on", "build a relationship",
              "build trust", "build character", "build confidence",
              "build bridges", "build from scratch", "build momentum",
              "build castles in the air"],
    "change": ["change one's mind", "change hands", "change the subject",
               "change for the better", "change gears", "change course",
               "change one's tune", "change lanes", "change direction",
               "change the game"],
    "develop": ["develop into", "develop a habit", "develop an interest in",
                "develop skills", "develop a plan", "develop over time",
                "develop a relationship", "develop a strategy",
                "develop from scratch", "develop new ideas"],
    "increase": ["increase in", "increase by", "increase dramatically",
                 "increase awareness", "increase productivity",
                 "increase the chances", "increase significantly",
                 "increase the risk", "increase pressure",
                 "increase in value"],
    "reduce": ["reduce to", "reduce by", "reduce the risk",
               "reduce costs", "reduce waste", "reduce stress",
               "reduce the impact", "reduce significantly",
               "reduce to tears", "reduce in size"],
    "improve": ["improve on", "improve the quality", "improve performance",
                "improve one's health", "improve significantly",
                "improve relations", "improve the situation",
                "improve one's skills", "improve over time",
                "improve upon"],
    "accept": ["accept responsibility", "accept an offer", "accept the challenge",
               "accept defeat", "accept the fact", "accept into",
               "accept as true", "accept with grace", "accept willingly",
               "accept the consequences"],
    "avoid": ["avoid doing", "avoid eye contact", "avoid the issue",
              "avoid risk", "avoid temptation", "avoid conflict",
              "avoid at all costs", "avoid detection", "avoid the subject",
              "avoid confrontation"],
    "consider": ["consider doing", "consider carefully", "consider the options",
                 "consider the consequences", "consider it done",
                 "consider a possibility", "consider the pros and cons",
                 "consider the impact", "consider seriously",
                 "consider oneself lucky"],
    "create": ["create a sense of", "create opportunities", "create awareness",
               "create jobs", "create confusion", "create a new",
               "create something out of nothing", "create tension",
               "create a buzz", "create value"],
    "continue": ["continue to do", "continue with", "continue on",
                 "continue the tradition", "continue to grow",
                 "continue despite", "continue indefinitely",
                 "continue the journey", "continue forward",
                 "continue to develop"],
    "provide": ["provide with", "provide for", "provide access to",
                "provide an opportunity", "provide support",
                "provide information", "provide evidence",
                "provide a solution", "provide protection",
                "provide guidance"],
    "require": ["require attention", "require effort", "require patience",
                "require skill", "require a permit", "require courage",
                "require explanation", "require immediate action",
                "require further investigation", "require maintenance"],
    "suggest": ["suggest doing", "suggest that", "suggest a way",
                "suggest strongly", "suggest an alternative",
                "suggest a solution", "suggest a plan",
                "suggest otherwise", "suggest the possibility",
                "suggest improvement"],
    "support": ["support the idea", "support a family", "support the claim",
                "support the cause", "support each other",
                "support the theory", "support system",
                "support financially", "support wholeheartedly",
                "support the argument"],
    "expect": ["expect to", "expect from", "expect the worst",
               "expect the best", "expect too much", "expect a lot",
               "expect a miracle", "expect the unexpected",
               "expect results", "expect perfection"],
    "enjoy": ["enjoy oneself", "enjoy the view", "enjoy a meal",
              "enjoy the company", "enjoy the moment", "enjoy life",
              "enjoy doing", "enjoy the benefits", "enjoy great popularity",
              "enjoy a reputation"],
    "achieve": ["achieve success", "achieve a goal", "achieve results",
                "achieve one's dream", "achieve great heights",
                "achieve balance", "achieve harmony", "achieve fame",
                "achieve recognition", "achieve the impossible"],
    "understand": ["understand the situation", "understand the meaning",
                   "understand the importance", "understand the concept",
                   "understand each other", "understand the difference",
                   "understand the implications", "understand clearly",
                   "understand the problem", "understand the basics"],
    "explain": ["explain the situation", "explain in detail",
                "explain the difference", "explain clearly",
                "explain the meaning", "explain the reason",
                "explain how to", "explain away", "explain oneself",
                "explain the process"],
    "describe": ["describe in detail", "describe as", "describe accurately",
                 "describe the situation", "describe the process",
                 "describe how", "describe what happened",
                 "describe the difference", "describe briefly",
                 "describe in one's own words"],
    "determine": ["determine the cause", "determine the outcome",
                  "determine whether", "determine the extent",
                  "determine the value", "determine the truth",
                  "determine the best way", "determine the future",
                  "determine for oneself", "determine the facts"],
    "establish": ["establish a connection", "establish contact",
                  "establish a relationship", "establish the facts",
                  "establish a framework", "establish credibility",
                  "establish a foundation", "establish rules",
                  "establish trust", "establish a pattern"],
    "recognize": ["recognize the importance", "recognize the need",
                  "recognize the signs", "recognize the difference",
                  "recognize as", "recognize the value",
                  "recognize the risk", "recognize one's efforts",
                  "recognize the truth", "recognize a pattern"],
    "discover": ["discover the truth", "discover new", "discover how to",
                 "discover the secret", "discover the meaning",
                 "discover a solution", "discover the cause",
                 "discover for oneself", "discover the joy of",
                 "discover the benefits"],
    "demonstrate": ["demonstrate how", "demonstrate the ability",
                    "demonstrate the importance", "demonstrate that",
                    "demonstrate the need", "demonstrate the value",
                    "demonstrate the effectiveness", "demonstrate courage",
                    "demonstrate commitment", "demonstrate skill"],
    "represent": ["represent a threat", "represent the interests",
                  "represent the best of", "represent a challenge",
                  "represent a significant", "represent an increase",
                  "represent the majority", "represent a turning point",
                  "represent in court", "represent oneself"],
    "indicate": ["indicate that", "indicate the presence",
                 "indicate a need", "indicate the direction",
                 "indicate clearly", "indicate the extent",
                 "indicate the importance", "indicate a trend",
                 "indicate willingness", "indicate the level"],
    "compare": ["compare with", "compare to", "compare notes",
                "compare and contrast", "compare favorably",
                "compare the differences", "compare prices",
                "compare options", "compare the two",
                "compare against"],
    "communicate": ["communicate with", "communicate effectively",
                    "communicate the message", "communicate clearly",
                    "communicate ideas", "communicate through",
                    "communicate the importance", "communicate openly",
                    "communicate the need", "communicate in writing"],

    # ── 名词 ──
    "time": ["in time", "on time", "time and again", "time flies",
             "have a good time", "in no time", "from time to time",
             "kill time", "save time", "waste of time"],
    "way": ["by the way", "in a way", "on the way", "under way",
            "no way", "by way of", "make way for", "give way",
            "out of the way", "in the way"],
    "life": ["come to life", "bring to life", "the life of the party",
             "a matter of life and death", "life goes on",
             "quality of life", "take one's life", "the good life",
             "change one's life", "life is short"],
    "world": ["in the world", "all over the world", "on top of the world",
              "out of this world", "the end of the world",
              "world of difference", "a whole new world",
              "change the world", "world-class", "in a world of one's own"],
    "day": ["day and night", "day by day", "in this day and age",
            "call it a day", "make one's day", "the other day",
            "one of these days", "from day one", "back in the day",
            "have seen better days"],
    "hand": ["on the other hand", "hand in hand", "by hand",
             "on hand", "lend a hand", "hands down",
             "out of hand", "take matters into one's hands",
             "wash one's hands of", "get out of hand"],
    "mind": ["keep in mind", "make up one's mind", "have in mind",
             "bear in mind", "cross one's mind", "blow one's mind",
             "mind one's own business", "never mind",
             "out of sight, out of mind", "mind the gap"],
    "place": ["in place", "out of place", "take place", "in the first place",
              "all over the place", "in place of", "go places",
              "a place to call home", "put oneself in someone's place",
              "if I were in your place"],
    "point": ["point of view", "case in point", "to the point",
              "make a point", "get the point", "up to a point",
              "point out", "point the finger at", "the point is",
              "miss the point"],
    "fact": ["as a matter of fact", "in fact", "the fact is",
             "despite the fact", "facts and figures", "face the facts",
             "the fact of the matter", "before the fact",
             "after the fact", "know for a fact"],
    "water": ["hold water", "in hot water", "like water off a duck's back",
              "water under the bridge", "come hell or high water",
              "throw cold water on", "water down", "tread water",
              "still waters run deep", "fish out of water"],
    "work": ["at work", "out of work", "hard work", "teamwork",
             "work in progress", "the works", "dirty work",
             "a work of art", "make short work of", "all in a day's work"],
    "power": ["in power", "come into power", "power of attorney",
              "the power of", "power struggle", "power outage",
              "empower", "power through", "the powers that be",
              "knowledge is power"],
    "change": ["change of heart", "loose change", "for a change",
               "a change is as good as a rest", "pocket change",
               "change of pace", "change of scenery",
               "wind of change", "ring the changes", "small change"],
    "problem": ["no problem", "have a problem with", "the problem is",
                "problem-solving", "face the problem", "tackle the problem",
                "run into a problem", "root of the problem",
                "pose a problem", "problem child"],
    "experience": ["from experience", "learn from experience",
                   "gain experience", "work experience",
                   "experience in", "hands-on experience",
                   "a rewarding experience", "wealth of experience",
                   "previous experience required", "share the experience"],
    "reason": ["for this reason", "by reason of", "within reason",
               "for some reason", "have reason to", "listen to reason",
               "stand to reason", "for no good reason",
               "the main reason", "give a reason"],
    "result": ["as a result", "as a result of", "end result",
               "result in", "result from", "get results",
               "net result", "final result", "without result",
               "result in failure"],
    "idea": ["have an idea", "the idea is", "get the idea",
             "give someone an idea", "bright idea", "the big idea",
             "run with an idea", "toy with an idea",
             "the general idea", "give an idea of"],
    "information": ["piece of information", "gather information",
                    "share information", "provide information",
                    "access to information", "for your information",
                    "background information", "first-hand information",
                    "classified information", "a wealth of information"],
    "opinion": ["in one's opinion", "have a high opinion of",
                "be of the opinion", "public opinion",
                "a matter of opinion", "expert opinion",
                "second opinion", "express an opinion",
                "opinion poll", "in my humble opinion"],
    "importance": ["of great importance", "attach importance to",
                   "stress the importance", "the importance of",
                   "of vital importance", "of particular importance",
                   "of minor importance", "understand the importance",
                   "emphasize the importance", "recognize the importance"],
    "relationship": ["in a relationship", "build a relationship",
                     "establish a relationship", "working relationship",
                     "personal relationship", "diplomatic relationship",
                     "in good relationship", "relationship between",
                     "break off a relationship", "long-term relationship"],
    "difference": ["make a difference", "tell the difference",
                   "the difference between", "world of difference",
                   "no different from", "difference of opinion",
                   "make no difference", "spot the difference",
                   "for all the difference it makes", "a big difference"],
    "effort": ["make an effort", "effort to", "put effort into",
               "with effort", "without effort", "in an effort to",
               "team effort", "a great effort", "spare no effort",
               "a waste of effort"],
    "interest": ["take an interest in", "in the interest of",
                 "a matter of interest", "of great interest",
                 "public interest", "conflict of interest",
                 "out of interest", "rate of interest",
                 "have no interest in", "spark interest"],

    # ── 形容词 ──
    "good": ["good at", "good for", "good morning", "as good as",
             "a good deal", "good enough", "good-looking",
             "good luck", "for good", "make good"],
    "bad": ["bad at", "bad for", "bad luck", "go from bad to worse",
            "bad blood", "bad temper", "feel bad about",
            "bad news", "not bad", "in a bad way"],
    "important": ["of great importance", "play an important role",
                  "important to note", "equally important",
                  "it is important that", "the most important thing",
                  "important factor", "important decision",
                  "important step", "important contribution"],
    "difficult": ["difficult to", "difficult situation",
                  "find it difficult", "difficult time",
                  "difficult task", "difficult choice",
                  "make things difficult", "increasingly difficult",
                  "difficult question", "difficult to believe"],
    "possible": ["as soon as possible", "make it possible",
                 "if possible", "everything is possible",
                 "possible outcome", "the only possible",
                 "whenever possible", "possible solution",
                 "as much as possible", "best possible"],
    "common": ["in common", "common sense", "common knowledge",
               "common ground", "have in common", "common practice",
               "common goal", "common interest", "common mistake",
               "nothing in common"],
    "able": ["be able to", "able to do", "able to handle",
             "able to cope", "able to see", "able to understand",
             "able to afford", "able to help", "able to manage",
             "able to provide"],
    "ready": ["get ready", "ready for", "ready to go",
              "ready to help", "at the ready", "ready and willing",
              "ready-made", "ready access", "ready to start",
              "always ready"],
    "likely": ["most likely", "likely to", "not likely",
               "likely outcome", "likely candidate", "likely cause",
               "likely story", "likely scenario", "more likely than not",
               "seem likely"],
    "sure": ["make sure", "for sure", "sure of", "sure enough",
             "sure thing", "not sure", "be sure to",
             "sure of oneself", "sure bet", "as sure as"],
    "different": ["different from", "different types of", "in a different way",
                  "different aspects", "different approach",
                  "different perspective", "different meaning",
                  "different altogether", "worlds apart",
                  "make a difference"],
    "similar": ["similar to", "similar situation", "similar type",
                "similar pattern", "in a similar way", "similar approach",
                "strikingly similar", "similar experience",
                "similar effect", "similar result"],
    "special": ["special occasion", "special attention", "special care",
                "special interest", "in particular", "special education",
                "special treatment", "special request",
                "nothing special", "specialize in"],
    "familiar": ["familiar with", "look familiar", "familiar face",
                 "familiar territory", "familiar ground",
                 "become familiar with", "familiar sound",
                 "overly familiar", "familiar pattern",
                 "familiarize oneself with"],
    "aware": ["be aware of", "aware of the risks", "well aware",
              "become aware", "aware of the need", "self-aware",
              "acutely aware", "painfully aware",
              "aware of the consequences", "make aware"],
    "responsible": ["responsible for", "be held responsible",
                    "responsible behavior", "responsible decision",
                    "take responsible action", "financially responsible",
                    "socially responsible", "responsible person",
                    "hold responsible", "responsible use"],
    "afraid": ["afraid of", "afraid to", "I'm afraid",
               "afraid of heights", "afraid of the dark",
               "nothing to be afraid of", "afraid to ask",
               "afraid so", "don't be afraid", "afraid not"],
    "capable": ["capable of", "highly capable", "capable person",
                "capable of doing", "more than capable",
                "barely capable", "prove capable",
                "capable leader", "capable hands",
                "capable of change"],
    "eager": ["eager to", "eager for", "eager beaver",
              "eager to learn", "eager to please", "eager anticipation",
              "eagerly await", "too eager", "eager participant",
              "eager to help"],
    "free": ["free from", "free to", "feel free",
             "for free", "free of charge", "free speech",
             "free time", "free will", "guilt-free",
             "carefree"],
    "full": ["full of", "in full", "full-time", "full speed",
             "at full capacity", "full stop", "full name",
             "full extent", "come full circle", "in full swing"],
    "worth": ["worth doing", "worth a try", "worth mentioning",
              "net worth", "worth the effort", "worth noting",
              "not worth it", "worth every penny", "self-worth",
              "worth one's while"],
    "aware": ["aware of", "become aware", "well aware", "self-aware",
              "environmentally aware", "awareness campaign",
              "awareness of", "make aware", "acutely aware",
              "painfully aware"],
    "popular": ["popular with", "popular among", "popular belief",
                "popular culture", "popular demand", "grow in popularity",
                "popular choice", "wildly popular", "popular opinion",
                "unpopular decision"],
    "clear": ["clear about", "make clear", "clear the air",
              "clear-cut", "clear conscience", "clear one's head",
              "crystal clear", "all clear", "clear the way",
              "clear to everyone"],
    "serious": ["serious about", "serious consequence", "serious concern",
                "serious matter", "serious illness", "dead serious",
                "nothing serious", "serious injury",
                "serious implications", "take seriously"],

    # ── 副词 ──
    "very": ["very much", "very well", "very important",
             "very quickly", "very soon", "very likely",
             "very good", "very few", "very little", "not very"],
    "quite": ["quite a few", "quite a lot", "quite right",
              "quite the opposite", "quite possibly",
              "quite the same", "quite sure", "quite frankly",
              "quite clear", "quite different"],
    "rather": ["rather than", "rather like", "or rather",
               "would rather", "rather too", "rather good",
               "rather a lot", "rather than not",
               "rather odd", "rather disappointing"],
    "even": ["even if", "even though", "even so", "even now",
             "even better", "even worse", "not even",
             "even more", "even less", "break even"],
    "still": ["still waters", "still life", "still the same",
              "stand still", "hold still", "still going strong",
              "still and all", "still remains", "keep still",
              "even still"],

    # ── 介词/连词 ──
    "despite": ["despite the fact", "despite everything",
                "despite all", "despite of", "despite appearances",
                "despite the odds", "despite this",
                "despite what", "despite oneself",
                "despite the rain"],
    "according": ["according to", "according as", "according to plan",
                  "according to schedule", "according to one's needs",
                  "according to the rules", "according to tradition",
                  "according to custom", "according to reports",
                  "according to expectations"],
    "regardless": ["regardless of", "carry on regardless",
                   "regardless of the outcome", "regardless of cost",
                   "regardless of the weather",
                   "regardless of the fact",
                   "regardless of one's opinion",
                   "regardless of the consequences",
                   "regardless of anything",
                   "regardless of the result"],
}


def get_collocations(word: str) -> List[str]:
    """获取单词的常用搭配列表。

    Args:
        word: 要查询的英语单词

    Returns:
        搭配短语列表，如果没有则返回空列表
    """
    if not word:
        return []
    w = word.lower().strip()
    return list(_COLLOCATIONS_DB.get(w, []))


def format_collocations(word: str) -> str:
    """格式化常用搭配为可读文本。

    Returns:
        例如: "常用搭配:\n  make a decision\n  make progress"
        如果无数据则返回空字符串。
    """
    colls = get_collocations(word)
    if not colls:
        return ""
    lines = ["常用搭配:"]
    for c in colls:
        lines.append(f"  • {c}")
    return "\n".join(lines)


def has_data(word: str) -> bool:
    """检查是否有该词的常用搭配数据。"""
    if not word:
        return False
    return word.lower().strip() in _COLLOCATIONS_DB
