"""近义词/反义词模块 — 显示相关词汇

Provides synonym and antonym lookups for common English words.
Uses a curated database of ~500 high-frequency words with their
synonyms and antonyms, plus morphological fallback for unknown words.
"""

from typing import Dict, List, Optional, Set


# ── 近义词/反义词数据库 ──
# Each entry: word → { "synonyms": [...], "antonyms": [...] }
_SYNONYM_ANTONYM_DB: Dict[str, Dict[str, List[str]]] = {
    # ── 形容词 ──
    "happy": {"synonyms": ["glad", "cheerful", "joyful", "pleased", "delighted"], "antonyms": ["sad", "unhappy", "miserable", "gloomy"]},
    "sad": {"synonyms": ["unhappy", "sorrowful", "gloomy", "melancholy"], "antonyms": ["happy", "joyful", "cheerful", "glad"]},
    "big": {"synonyms": ["large", "huge", "enormous", "vast", "massive"], "antonyms": ["small", "tiny", "little", "miniature"]},
    "small": {"synonyms": ["tiny", "little", "miniature", "compact", "petite"], "antonyms": ["big", "large", "huge", "enormous"]},
    "good": {"synonyms": ["excellent", "fine", "great", "superb", "wonderful"], "antonyms": ["bad", "poor", "terrible", "awful"]},
    "bad": {"synonyms": ["poor", "terrible", "awful", "dreadful", "horrible"], "antonyms": ["good", "excellent", "great", "fine"]},
    "fast": {"synonyms": ["quick", "rapid", "swift", "speedy", "hasty"], "antonyms": ["slow", "sluggish", "leisurely"]},
    "slow": {"synonyms": ["sluggish", "leisurely", "gradual", "unhurried"], "antonyms": ["fast", "quick", "rapid", "swift"]},
    "hot": {"synonyms": ["warm", "heated", "scorching", "boiling", "fiery"], "antonyms": ["cold", "cool", "freezing", "chilly"]},
    "cold": {"synonyms": ["cool", "chilly", "freezing", "frigid", "icy"], "antonyms": ["hot", "warm", "heated", "boiling"]},
    "new": {"synonyms": ["fresh", "recent", "modern", "novel", "innovative"], "antonyms": ["old", "ancient", "outdated", "antique"]},
    "old": {"synonyms": ["ancient", "aged", "elderly", "vintage", "antique"], "antonyms": ["new", "young", "fresh", "modern"]},
    "easy": {"synonyms": ["simple", "effortless", "straightforward", "uncomplicated"], "antonyms": ["difficult", "hard", "challenging", "tough"]},
    "difficult": {"synonyms": ["hard", "challenging", "tough", "complex", "demanding"], "antonyms": ["easy", "simple", "effortless"]},
    "hard": {"synonyms": ["difficult", "challenging", "tough", "demanding"], "antonyms": ["easy", "simple", "soft"]},
    "soft": {"synonyms": ["gentle", "tender", "smooth", "delicate", "plush"], "antonyms": ["hard", "rough", "firm", "solid"]},
    "strong": {"synonyms": ["powerful", "mighty", "robust", "sturdy", "intense"], "antonyms": ["weak", "feeble", "fragile", "frail"]},
    "weak": {"synonyms": ["feeble", "fragile", "frail", "delicate", "faint"], "antonyms": ["strong", "powerful", "robust", "mighty"]},
    "rich": {"synonyms": ["wealthy", "affluent", "prosperous", "opulent"], "antonyms": ["poor", "impoverished", "broke", "destitute"]},
    "poor": {"synonyms": ["impoverished", "destitute", "needy", "broke"], "antonyms": ["rich", "wealthy", "affluent", "prosperous"]},
    "beautiful": {"synonyms": ["gorgeous", "stunning", "lovely", "elegant", "attractive"], "antonyms": ["ugly", "hideous", "unattractive", "plain"]},
    "ugly": {"synonyms": ["hideous", "unattractive", "plain", "grotesque"], "antonyms": ["beautiful", "gorgeous", "lovely", "attractive"]},
    "important": {"synonyms": ["significant", "crucial", "vital", "essential", "key"], "antonyms": ["unimportant", "trivial", "insignificant", "minor"]},
    "interesting": {"synonyms": ["fascinating", "intriguing", "engaging", "compelling"], "antonyms": ["boring", "dull", "tedious", "uninteresting"]},
    "boring": {"synonyms": ["dull", "tedious", "monotonous", "tiresome"], "antonyms": ["interesting", "fascinating", "exciting", "engaging"]},
    "angry": {"synonyms": ["furious", "enraged", "irate", "outraged", "livid"], "antonyms": ["calm", "peaceful", "pleased", "content"]},
    "calm": {"synonyms": ["peaceful", "serene", "tranquil", "relaxed", "composed"], "antonyms": ["angry", "agitated", "anxious", "nervous"]},
    "afraid": {"synonyms": ["scared", "frightened", "terrified", "fearful", "anxious"], "antonyms": ["brave", "fearless", "bold", "courageous"]},
    "brave": {"synonyms": ["courageous", "fearless", "bold", "valiant", "heroic"], "antonyms": ["afraid", "cowardly", "timid", "fearful"]},
    "clever": {"synonyms": ["smart", "intelligent", "brilliant", "wise", "sharp"], "antonyms": ["stupid", "foolish", "dull", "ignorant"]},
    "stupid": {"synonyms": ["foolish", "dull", "ignorant", "dense", "dim"], "antonyms": ["clever", "smart", "intelligent", "wise"]},
    "clean": {"synonyms": ["spotless", "pure", "tidy", "immaculate", "sanitary"], "antonyms": ["dirty", "filthy", "messy", "contaminated"]},
    "dirty": {"synonyms": ["filthy", "messy", "grimy", "soiled", "contaminated"], "antonyms": ["clean", "spotless", "pure", "tidy"]},
    "dark": {"synonyms": ["dim", "gloomy", "shadowy", "obscure", "murky"], "antonyms": ["bright", "light", "luminous", "radiant"]},
    "bright": {"synonyms": ["luminous", "radiant", "brilliant", "vivid", "shining"], "antonyms": ["dark", "dim", "dull", "gloomy"]},
    "quiet": {"synonyms": ["silent", "peaceful", "hushed", "mute", "serene"], "antonyms": ["loud", "noisy", "boisterous", "clamorous"]},
    "loud": {"synonyms": ["noisy", "boisterous", "thunderous", "deafening"], "antonyms": ["quiet", "silent", "soft", "hushed"]},
    "wet": {"synonyms": ["damp", "moist", "soaked", "drenched", "saturated"], "antonyms": ["dry", "arid", "parched"]},
    "dry": {"synonyms": ["arid", "parched", "dehydrated", "barren"], "antonyms": ["wet", "damp", "moist", "soaked"]},
    "full": {"synonyms": ["complete", "entire", "whole", "packed", "loaded"], "antonyms": ["empty", "vacant", "hollow", "bare"]},
    "empty": {"synonyms": ["vacant", "hollow", "bare", "void", "blank"], "antonyms": ["full", "complete", "packed", "loaded"]},
    "wide": {"synonyms": ["broad", "expansive", "vast", "spacious", "extensive"], "antonyms": ["narrow", "thin", "slim", "tight"]},
    "narrow": {"synonyms": ["thin", "slim", "tight", "slender", "constricted"], "antonyms": ["wide", "broad", "expansive", "vast"]},
    "thick": {"synonyms": ["dense", "stout", "chunky", "heavy", "substantial"], "antonyms": ["thin", "slim", "slender", "fine"]},
    "thin": {"synonyms": ["slim", "slender", "lean", "narrow", "fine"], "antonyms": ["thick", "fat", "wide", "heavy"]},
    "deep": {"synonyms": ["profound", "intense", "abysmal", "bottomless"], "antonyms": ["shallow", "superficial", "surface"]},
    "shallow": {"synonyms": ["superficial", "surface", "skin-deep"], "antonyms": ["deep", "profound", "intense"]},
    "sharp": {"synonyms": ["keen", "acute", "pointed", "piercing", "crisp"], "antonyms": ["blunt", "dull", "rounded"]},
    "blunt": {"synonyms": ["dull", "rounded", "obtuse"], "antonyms": ["sharp", "keen", "pointed"]},
    "long": {"synonyms": ["lengthy", "extended", "prolonged", "protracted"], "antonyms": ["short", "brief", "concise"]},
    "short": {"synonyms": ["brief", "concise", "compact", "abbreviated"], "antonyms": ["long", "lengthy", "extended", "tall"]},
    "tall": {"synonyms": ["high", "lofty", "towering", "elevated"], "antonyms": ["short", "low", "small"]},
    "early": {"synonyms": ["premature", "advance", "ahead of schedule"], "antonyms": ["late", "delayed", "overdue"]},
    "late": {"synonyms": ["delayed", "overdue", "tardy", "belated"], "antonyms": ["early", "timely", "prompt"]},
    "young": {"synonyms": ["youthful", "juvenile", "adolescent", "junior"], "antonyms": ["old", "elderly", "aged", "senior"]},
    "safe": {"synonyms": ["secure", "protected", "harmless", "reliable"], "antonyms": ["dangerous", "risky", "hazardous", "unsafe"]},
    "dangerous": {"synonyms": ["risky", "hazardous", "perilous", "treacherous"], "antonyms": ["safe", "secure", "harmless"]},
    "correct": {"synonyms": ["right", "accurate", "precise", "exact", "proper"], "antonyms": ["wrong", "incorrect", "inaccurate", "false"]},
    "wrong": {"synonyms": ["incorrect", "inaccurate", "false", "mistaken", "erroneous"], "antonyms": ["correct", "right", "accurate", "true"]},
    "true": {"synonyms": ["accurate", "genuine", "real", "authentic", "valid"], "antonyms": ["false", "untrue", "wrong", "fake"]},
    "false": {"synonyms": ["untrue", "wrong", "fake", "artificial", "bogus"], "antonyms": ["true", "genuine", "real", "authentic"]},
    "free": {"synonyms": ["liberated", "independent", "unrestricted", "complimentary"], "antonyms": ["bound", "restricted", "captive", "paid"]},
    "busy": {"synonyms": ["occupied", "engaged", "active", "bustling"], "antonyms": ["idle", "free", "inactive", "unoccupied"]},
    "open": {"synonyms": ["unlocked", "accessible", "available", "exposed"], "antonyms": ["closed", "shut", "sealed", "locked"]},
    "closed": {"synonyms": ["shut", "sealed", "locked", "barred"], "antonyms": ["open", "unlocked", "accessible"]},
    "fair": {"synonyms": ["just", "equitable", "impartial", "reasonable"], "antonyms": ["unfair", "biased", "unjust", "partial"]},
    "kind": {"synonyms": ["gentle", "caring", "compassionate", "benevolent", "generous"], "antonyms": ["cruel", "mean", "harsh", "heartless"]},
    "cruel": {"synonyms": ["brutal", "heartless", "vicious", "merciless", "ruthless"], "antonyms": ["kind", "compassionate", "merciful", "gentle"]},
    "wise": {"synonyms": ["sage", "prudent", "sensible", "knowledgeable"], "antonyms": ["foolish", "unwise", "imprudent"]},
    "foolish": {"synonyms": ["silly", "unwise", "absurd", "ridiculous"], "antonyms": ["wise", "sensible", "prudent"]},
    "famous": {"synonyms": ["renowned", "celebrated", "well-known", "notable", "prominent"], "antonyms": ["unknown", "obscure", "anonymous"]},
    "common": {"synonyms": ["frequent", "usual", "ordinary", "typical", "widespread"], "antonyms": ["rare", "uncommon", "unusual", "unique"]},
    "rare": {"synonyms": ["uncommon", "unusual", "scarce", "infrequent", "unique"], "antonyms": ["common", "frequent", "usual", "typical"]},
    "simple": {"synonyms": ["easy", "basic", "straightforward", "plain", "modest"], "antonyms": ["complex", "complicated", "elaborate", "difficult"]},
    "complex": {"synonyms": ["complicated", "elaborate", "intricate", "sophisticated"], "antonyms": ["simple", "easy", "basic"]},
    "clear": {"synonyms": ["obvious", "apparent", "evident", "transparent", "distinct"], "antonyms": ["unclear", "vague", "ambiguous", "obscure"]},
    "vague": {"synonyms": ["unclear", "ambiguous", "obscure", "hazy", "indefinite"], "antonyms": ["clear", "precise", "definite", "explicit"]},
    "modern": {"synonyms": ["contemporary", "current", "recent", "up-to-date", "fashionable"], "antonyms": ["ancient", "old-fashioned", "traditional", "outdated"]},
    "traditional": {"synonyms": ["conventional", "classic", "customary", "established"], "antonyms": ["modern", "innovative", "progressive", "novel"]},
    "familiar": {"synonyms": ["well-known", "recognizable", "common", "accustomed"], "antonyms": ["unfamiliar", "strange", "foreign", "unknown"]},
    "strange": {"synonyms": ["unusual", "odd", "peculiar", "weird", "bizarre"], "antonyms": ["familiar", "normal", "usual", "ordinary"]},
    "normal": {"synonyms": ["usual", "typical", "standard", "regular", "ordinary"], "antonyms": ["abnormal", "unusual", "strange", "irregular"]},
    "perfect": {"synonyms": ["flawless", "ideal", "excellent", "impeccable", "faultless"], "antonyms": ["imperfect", "flawed", "defective"]},
    "similar": {"synonyms": ["alike", "comparable", "analogous", "equivalent"], "antonyms": ["different", "dissimilar", "unlike", "distinct"]},
    "different": {"synonyms": ["distinct", "diverse", "unlike", "varied", "dissimilar"], "antonyms": ["similar", "alike", "same", "identical"]},
    "special": {"synonyms": ["unique", "particular", "exceptional", "distinctive", "notable"], "antonyms": ["ordinary", "common", "regular", "normal"]},
    "surprised": {"synonyms": ["astonished", "amazed", "shocked", "startled", "stunned"], "antonyms": ["unsurprised", "expecting"]},
    "tired": {"synonyms": ["exhausted", "weary", "fatigued", "drained", "worn out"], "antonyms": ["energetic", "refreshed", "rested", "vigorous"]},
    "energetic": {"synonyms": ["lively", "vigorous", "dynamic", "spirited", "active"], "antonyms": ["tired", "exhausted", "lethargic", "sluggish"]},
    "confident": {"synonyms": ["assured", "self-assured", "bold", "certain", "poised"], "antonyms": ["insecure", "uncertain", "doubtful", "timid"]},
    "nervous": {"synonyms": ["anxious", "uneasy", "tense", "apprehensive", "jittery"], "antonyms": ["calm", "relaxed", "confident", "composed"]},
    "lonely": {"synonyms": ["isolated", "alone", "solitary", "forlorn", "desolate"], "antonyms": ["popular", "sociable", "accompanied"]},
    "polite": {"synonyms": ["courteous", "respectful", "mannerly", "civil", "gracious"], "antonyms": ["rude", "impolite", "discourteous", "insolent"]},
    "rude": {"synonyms": ["impolite", "discourteous", "insolent", "disrespectful"], "antonyms": ["polite", "courteous", "respectful", "gracious"]},
    "generous": {"synonyms": ["charitable", "giving", "liberal", "benevolent", "munificent"], "antonyms": ["stingy", "selfish", "greedy", "miserly"]},
    "selfish": {"synonyms": ["egotistical", "self-centered", "greedy", "stingy"], "antonyms": ["generous", "selfless", "altruistic", "giving"]},
    "honest": {"synonyms": ["truthful", "sincere", "candid", "genuine", "trustworthy"], "antonyms": ["dishonest", "deceitful", "lying", "corrupt"]},
    "proud": {"synonyms": ["arrogant", "conceited", "vain", "dignified", "confident"], "antonyms": ["humble", "modest", "meek"]},
    "humble": {"synonyms": ["modest", "meek", "unassuming", "down-to-earth"], "antonyms": ["proud", "arrogant", "conceited", "boastful"]},
    "lazy": {"synonyms": ["idle", "sluggish", "indolent", "inactive", "lethargic"], "antonyms": ["industrious", "hardworking", "diligent", "active"]},
    "diligent": {"synonyms": ["industrious", "hardworking", "dedicated", "thorough", "conscientious"], "antonyms": ["lazy", "idle", "negligent"]},
    "certain": {"synonyms": ["sure", "confident", "definite", "positive", "convinced"], "antonyms": ["uncertain", "doubtful", "unsure", "unclear"]},
    "possible": {"synonyms": ["feasible", "potential", "achievable", "conceivable"], "antonyms": ["impossible", "unlikely", "unfeasible"]},
    "impossible": {"synonyms": ["unachievable", "hopeless", "impractical", "unattainable"], "antonyms": ["possible", "feasible", "achievable"]},
    "pleasant": {"synonyms": ["enjoyable", "agreeable", "delightful", "nice", "pleasing"], "antonyms": ["unpleasant", "disagreeable", "nasty"]},
    "unpleasant": {"synonyms": ["disagreeable", "nasty", "offensive", "distasteful"], "antonyms": ["pleasant", "enjoyable", "agreeable"]},
    "fierce": {"synonyms": ["ferocious", "aggressive", "intense", "savage", "violent"], "antonyms": ["gentle", "mild", "tame", "docile"]},
    "gentle": {"synonyms": ["mild", "tender", "soft", "delicate", "kind"], "antonyms": ["harsh", "rough", "fierce", "violent"]},
    "fresh": {"synonyms": ["new", "crisp", "refreshing", "original", "renewed"], "antonyms": ["stale", "old", "worn", "outdated"]},
    "stale": {"synonyms": ["old", "musty", "flat", "worn-out"], "antonyms": ["fresh", "new", "crisp"]},
    "useful": {"synonyms": ["helpful", "beneficial", "valuable", "practical", "handy"], "antonyms": ["useless", "worthless", "pointless"]},
    "useless": {"synonyms": ["worthless", "pointless", "futile", "ineffective"], "antonyms": ["useful", "helpful", "valuable"]},
    "curious": {"synonyms": ["inquisitive", "interested", "eager", "nosy"], "antonyms": ["indifferent", "apathetic", "uninterested"]},
    "creative": {"synonyms": ["inventive", "imaginative", "innovative", "artistic"], "antonyms": ["unimaginative", "conventional", "ordinary"]},
    "careful": {"synonyms": ["cautious", "attentive", "thorough", "meticulous", "vigilant"], "antonyms": ["careless", "reckless", "negligent"]},
    "careless": {"synonyms": ["reckless", "negligent", "inattentive", "sloppy"], "antonyms": ["careful", "cautious", "meticulous"]},
    "powerful": {"synonyms": ["mighty", "potent", "forceful", "influential", "dominant"], "antonyms": ["powerless", "weak", "feeble"]},
    "harmful": {"synonyms": ["damaging", "detrimental", "injurious", "destructive"], "antonyms": ["harmless", "beneficial", "helpful"]},
    "harmless": {"synonyms": ["innocent", "safe", "inoffensive", "benign"], "antonyms": ["harmful", "dangerous", "destructive"]},
    "successful": {"synonyms": ["triumphant", "prosperous", "effective", "productive"], "antonyms": ["unsuccessful", "failed", "futile"]},
    "popular": {"synonyms": ["well-liked", "famous", "fashionable", "trendy", "beloved"], "antonyms": ["unpopular", "disliked", "obscure"]},
    "patient": {"synonyms": ["tolerant", "calm", "composed", "enduring", "forbearing"], "antonyms": ["impatient", "restless", "anxious"]},
    "impatient": {"synonyms": ["restless", "anxious", "eager", "hasty", "intolerant"], "antonyms": ["patient", "calm", "tolerant"]},
    "flexible": {"synonyms": ["adaptable", "versatile", "elastic", "pliable", "open-minded"], "antonyms": ["rigid", "inflexible", "stiff", "stubborn"]},
    "rigid": {"synonyms": ["inflexible", "stiff", "strict", "rigorous", "unyielding"], "antonyms": ["flexible", "adaptable", "pliable"]},
    "accurate": {"synonyms": ["precise", "exact", "correct", "faithful", "reliable"], "antonyms": ["inaccurate", "wrong", "imprecise"]},
    "adequate": {"synonyms": ["sufficient", "enough", "satisfactory", "acceptable"], "antonyms": ["inadequate", "insufficient", "lacking"]},
    "appropriate": {"synonyms": ["suitable", "fitting", "proper", "apt", "relevant"], "antonyms": ["inappropriate", "unsuitable", "wrong"]},
    "aware": {"synonyms": ["conscious", "informed", "alert", "knowledgeable"], "antonyms": ["unaware", "ignorant", "oblivious"]},
    "capable": {"synonyms": ["competent", "skilled", "able", "proficient", "talented"], "antonyms": ["incapable", "incompetent", "unable"]},
    "consistent": {"synonyms": ["steady", "uniform", "constant", "reliable"], "antonyms": ["inconsistent", "irregular", "unpredictable"]},
    "content": {"synonyms": ["satisfied", "pleased", "gratified", "at ease"], "antonyms": ["discontent", "dissatisfied", "unhappy"]},
    "eager": {"synonyms": ["enthusiastic", "keen", "anxious", "avid", "zealous"], "antonyms": ["indifferent", "reluctant", "apathetic"]},
    "efficient": {"synonyms": ["effective", "productive", "competent", "streamlined"], "antonyms": ["inefficient", "wasteful", "unproductive"]},
    "enormous": {"synonyms": ["huge", "vast", "immense", "gigantic", "colossal"], "antonyms": ["tiny", "small", "miniature"]},
    "entire": {"synonyms": ["whole", "complete", "full", "total", "absolute"], "antonyms": ["partial", "incomplete", "fragmentary"]},
    "equal": {"synonyms": ["identical", "same", "equivalent", "comparable"], "antonyms": ["unequal", "different", "disparate"]},
    "essential": {"synonyms": ["vital", "crucial", "indispensable", "necessary", "fundamental"], "antonyms": ["unnecessary", "optional", "trivial"]},
    "frequent": {"synonyms": ["common", "regular", "repeated", "habitual"], "antonyms": ["rare", "infrequent", "occasional"]},
    "guilty": {"synonyms": ["culpable", "blameworthy", "responsible", "at fault"], "antonyms": ["innocent", "blameless", "guiltless"]},
    "innocent": {"synonyms": ["blameless", "guiltless", "pure", "naive"], "antonyms": ["guilty", "culpable", "responsible"]},
    "mature": {"synonyms": ["adult", "grown-up", "developed", "ripe", "seasoned"], "antonyms": ["immature", "childish", "young"]},
    "obvious": {"synonyms": ["clear", "apparent", "evident", "plain", "transparent"], "antonyms": ["obscure", "hidden", "subtle", "unclear"]},
    "permanent": {"synonyms": ["lasting", "enduring", "eternal", "stable", "fixed"], "antonyms": ["temporary", "transient", "impermanent"]},
    "temporary": {"synonyms": ["transient", "brief", "short-lived", "provisional"], "antonyms": ["permanent", "lasting", "enduring"]},
    "relevant": {"synonyms": ["pertinent", "applicable", "related", "apposite"], "antonyms": ["irrelevant", "unrelated", "immaterial"]},
    "responsible": {"synonyms": ["accountable", "liable", "dependable", "trustworthy"], "antonyms": ["irresponsible", "careless", "negligent"]},
    "severe": {"synonyms": ["serious", "strict", "harsh", "intense", "extreme"], "antonyms": ["mild", "gentle", "lenient", "moderate"]},
    "significant": {"synonyms": ["important", "notable", "meaningful", "considerable"], "antonyms": ["insignificant", "trivial", "minor"]},
    "stable": {"synonyms": ["steady", "firm", "secure", "constant", "reliable"], "antonyms": ["unstable", "unsteady", "volatile"]},
    "sufficient": {"synonyms": ["adequate", "enough", "ample", "satisfactory"], "antonyms": ["insufficient", "inadequate", "lacking"]},
    "superior": {"synonyms": ["better", "finer", "higher", "excellent", "supreme"], "antonyms": ["inferior", "lesser", "worse"]},
    "valid": {"synonyms": ["legitimate", "sound", "reasonable", "authentic"], "antonyms": ["invalid", "illegitimate", "void"]},
    "valuable": {"synonyms": ["precious", "worthwhile", "prized", "priceless"], "antonyms": ["worthless", "valueless", "cheap"]},
    "visible": {"synonyms": ["apparent", "observable", "noticeable", "evident"], "antonyms": ["invisible", "hidden", "unseen"]},
    "vital": {"synonyms": ["essential", "crucial", "critical", "indispensable"], "antonyms": ["unnecessary", "unimportant", "trivial"]},
    "vivid": {"synonyms": ["bright", "striking", "intense", "graphic", "lively"], "antonyms": ["dull", "faded", "dim", "pale"]},

    # ── 动词 ──
    "accept": {"synonyms": ["receive", "welcome", "embrace", "adopt"], "antonyms": ["reject", "refuse", "decline"]},
    "reject": {"synonyms": ["refuse", "decline", "deny", "dismiss"], "antonyms": ["accept", "welcome", "embrace"]},
    "achieve": {"synonyms": ["accomplish", "attain", "reach", "fulfill", "realize"], "antonyms": ["fail", "miss", "lose"]},
    "fail": {"synonyms": ["falter", "stumble", "flunk", "collapse"], "antonyms": ["succeed", "achieve", "triumph"]},
    "add": {"synonyms": ["include", "append", "insert", "supplement"], "antonyms": ["remove", "subtract", "delete"]},
    "remove": {"synonyms": ["eliminate", "delete", "extract", "eradicate"], "antonyms": ["add", "insert", "include"]},
    "advance": {"synonyms": ["progress", "proceed", "move forward", "develop"], "antonyms": ["retreat", "regress", "recede"]},
    "retreat": {"synonyms": ["withdraw", "retire", "recede", "back off"], "antonyms": ["advance", "progress", "attack"]},
    "agree": {"synonyms": ["concur", "consent", "approve", "accept"], "antonyms": ["disagree", "refuse", "oppose"]},
    "disagree": {"synonyms": ["differ", "oppose", "contest", "dispute"], "antonyms": ["agree", "concur", "consent"]},
    "allow": {"synonyms": ["permit", "authorize", "let", "enable"], "antonyms": ["forbid", "prohibit", "ban"]},
    "forbid": {"synonyms": ["prohibit", "ban", "bar", "disallow"], "antonyms": ["allow", "permit", "authorize"]},
    "appear": {"synonyms": ["emerge", "surface", "show up", "materialize"], "antonyms": ["disappear", "vanish", "fade"]},
    "disappear": {"synonyms": ["vanish", "fade", "evaporate", "dissolve"], "antonyms": ["appear", "emerge", "surface"]},
    "arrive": {"synonyms": ["reach", "come", "appear", "land"], "antonyms": ["leave", "depart", "go"]},
    "leave": {"synonyms": ["depart", "go", "exit", "vacate"], "antonyms": ["arrive", "come", "stay", "remain"]},
    "attack": {"synonyms": ["assault", "strike", "charge", "offensive"], "antonyms": ["defend", "protect", "guard"]},
    "defend": {"synonyms": ["protect", "guard", "shield", "safeguard"], "antonyms": ["attack", "assault", "threaten"]},
    "begin": {"synonyms": ["start", "commence", "initiate", "launch"], "antonyms": ["end", "finish", "conclude"]},
    "end": {"synonyms": ["finish", "conclude", "terminate", "cease"], "antonyms": ["begin", "start", "commence"]},
    "build": {"synonyms": ["construct", "create", "assemble", "erect"], "antonyms": ["destroy", "demolish", "ruin"]},
    "destroy": {"synonyms": ["demolish", "ruin", "wreck", "annihilate"], "antonyms": ["build", "construct", "create"]},
    "buy": {"synonyms": ["purchase", "acquire", "procure", "obtain"], "antonyms": ["sell", "vend", "trade"]},
    "sell": {"synonyms": ["vend", "trade", "market", "merchandise"], "antonyms": ["buy", "purchase", "acquire"]},
    "carry": {"synonyms": ["bear", "transport", "convey", "haul"], "antonyms": ["drop", "discard", "abandon"]},
    "change": {"synonyms": ["alter", "modify", "transform", "adjust"], "antonyms": ["keep", "maintain", "preserve"]},
    "keep": {"synonyms": ["maintain", "preserve", "retain", "hold"], "antonyms": ["discard", "release", "abandon"]},
    "choose": {"synonyms": ["select", "pick", "elect", "opt for"], "antonyms": ["reject", "refuse", "decline"]},
    "claim": {"synonyms": ["assert", "declare", "maintain", "contend"], "antonyms": ["deny", "disclaim", "reject"]},
    "deny": {"synonyms": ["reject", "refuse", "contradict", "disclaim"], "antonyms": ["admit", "acknowledge", "confirm"]},
    "collect": {"synonyms": ["gather", "accumulate", "amass", "assemble"], "antonyms": ["scatter", "distribute", "disperse"]},
    "compare": {"synonyms": ["contrast", "match", "relate", "liken"], "antonyms": ["contrast"]},
    "connect": {"synonyms": ["link", "join", "attach", "unite"], "antonyms": ["disconnect", "separate", "detach"]},
    "contain": {"synonyms": ["include", "hold", "comprise", "encompass"], "antonyms": ["exclude", "lack"]},
    "continue": {"synonyms": ["persist", "proceed", "resume", "carry on"], "antonyms": ["stop", "cease", "halt"]},
    "stop": {"synonyms": ["cease", "halt", "discontinue", "pause"], "antonyms": ["continue", "start", "begin"]},
    "create": {"synonyms": ["make", "produce", "generate", "craft", "design"], "antonyms": ["destroy", "demolish", "ruin"]},
    "damage": {"synonyms": ["harm", "injure", "impair", "mar"], "antonyms": ["repair", "fix", "restore"]},
    "repair": {"synonyms": ["fix", "mend", "restore", "patch"], "antonyms": ["damage", "break", "ruin"]},
    "decide": {"synonyms": ["determine", "resolve", "conclude", "choose"], "antonyms": ["hesitate", "waver"]},
    "decrease": {"synonyms": ["reduce", "diminish", "lessen", "shrink"], "antonyms": ["increase", "grow", "expand"]},
    "increase": {"synonyms": ["grow", "expand", "rise", "boost", "enhance"], "antonyms": ["decrease", "reduce", "diminish"]},
    "deliver": {"synonyms": ["transport", "carry", "distribute", "convey"], "antonyms": ["receive", "collect"]},
    "describe": {"synonyms": ["explain", "depict", "illustrate", "portray"], "antonyms": ["conceal", "hide"]},
    "develop": {"synonyms": ["evolve", "grow", "progress", "advance"], "antonyms": ["decline", "regress", "stagnate"]},
    "discover": {"synonyms": ["find", "uncover", "detect", "reveal"], "antonyms": ["miss", "overlook", "conceal"]},
    "divide": {"synonyms": ["split", "separate", "partition", "segment"], "antonyms": ["combine", "merge", "unite"]},
    "encourage": {"synonyms": ["motivate", "inspire", "support", "promote"], "antonyms": ["discourage", "deter", "dissuade"]},
    "discourage": {"synonyms": ["deter", "dissuade", "demoralize", "dishearten"], "antonyms": ["encourage", "motivate", "inspire"]},
    "enjoy": {"synonyms": ["relish", "savor", "appreciate", "delight in"], "antonyms": ["dislike", "hate", "detest"]},
    "hate": {"synonyms": ["despise", "loathe", "detest", "abhor"], "antonyms": ["love", "like", "adore"]},
    "love": {"synonyms": ["adore", "cherish", "treasure", "worship"], "antonyms": ["hate", "despise", "loathe"]},
    "estimate": {"synonyms": ["approximate", "gauge", "assess", "evaluate"], "antonyms": []},
    "examine": {"synonyms": ["inspect", "analyze", "scrutinize", "investigate"], "antonyms": ["ignore", "overlook"]},
    "exist": {"synonyms": ["live", "be", "survive", "persist"], "antonyms": ["vanish", "disappear", "perish"]},
    "expand": {"synonyms": ["grow", "enlarge", "extend", "broaden"], "antonyms": ["shrink", "contract", "reduce"]},
    "expect": {"synonyms": ["anticipate", "await", "predict", "foresee"], "antonyms": []},
    "explain": {"synonyms": ["clarify", "elaborate", "describe", "interpret"], "antonyms": ["confuse", "complicate"]},
    "express": {"synonyms": ["communicate", "convey", "articulate", "voice"], "antonyms": ["suppress", "conceal", "hide"]},
    "feed": {"synonyms": ["nourish", "nurture", "sustain", "provide"], "antonyms": ["starve"]},
    "fight": {"synonyms": ["combat", "battle", "struggle", "clash"], "antonyms": ["surrender", "yield", "cooperate"]},
    "follow": {"synonyms": ["pursue", "trail", "accompany", "obey"], "antonyms": ["lead", "precede", "guide"]},
    "lead": {"synonyms": ["guide", "direct", "head", "steer"], "antonyms": ["follow", "trail", "obey"]},
    "force": {"synonyms": ["compel", "oblige", "coerce", "pressure"], "antonyms": ["allow", "permit"]},
    "forget": {"synonyms": ["overlook", "neglect", "disregard"], "antonyms": ["remember", "recall", "recollect"]},
    "remember": {"synonyms": ["recall", "recollect", "reminisce"], "antonyms": ["forget", "overlook"]},
    "gain": {"synonyms": ["acquire", "obtain", "earn", "win"], "antonyms": ["lose", "forfeit", "surrender"]},
    "lose": {"synonyms": ["misplace", "forfeit", "surrender", "drop"], "antonyms": ["gain", "win", "find"]},
    "guess": {"synonyms": ["estimate", "speculate", "conjecture", "surmise"], "antonyms": []},
    "help": {"synonyms": ["assist", "aid", "support", "facilitate"], "antonyms": ["hinder", "obstruct", "impede"]},
    "hinder": {"synonyms": ["obstruct", "impede", "hamper", "block"], "antonyms": ["help", "assist", "facilitate"]},
    "hide": {"synonyms": ["conceal", "cover", "mask", "disguise"], "antonyms": ["reveal", "show", "expose"]},
    "reveal": {"synonyms": ["show", "expose", "disclose", "uncover"], "antonyms": ["hide", "conceal", "cover"]},
    "hold": {"synonyms": ["grasp", "grip", "clutch", "retain"], "antonyms": ["release", "drop", "let go"]},
    "release": {"synonyms": ["free", "liberate", "let go", "discharge"], "antonyms": ["hold", "capture", "detain"]},
    "hope": {"synonyms": ["wish", "desire", "aspire", "expect"], "antonyms": ["despair"]},
    "identify": {"synonyms": ["recognize", "distinguish", "determine", "pinpoint"], "antonyms": ["confuse", "mistake"]},
    "ignore": {"synonyms": ["disregard", "overlook", "neglect", "dismiss"], "antonyms": ["notice", "acknowledge", "heed"]},
    "imagine": {"synonyms": ["envision", "visualize", "conceive", "fantasize"], "antonyms": []},
    "improve": {"synonyms": ["enhance", "upgrade", "refine", "better"], "antonyms": ["worsen", "deteriorate", "degrade"]},
    "worsen": {"synonyms": ["deteriorate", "degrade", "decline"], "antonyms": ["improve", "enhance", "better"]},
    "include": {"synonyms": ["contain", "encompass", "incorporate", "involve"], "antonyms": ["exclude", "omit"]},
    "exclude": {"synonyms": ["omit", "bar", "reject", "eliminate"], "antonyms": ["include", "contain"]},
    "influence": {"synonyms": ["affect", "impact", "shape", "sway"], "antonyms": []},
    "inform": {"synonyms": ["notify", "tell", "advise", "alert"], "antonyms": ["conceal", "withhold"]},
    "insist": {"synonyms": ["demand", "assert", "persist", "maintain"], "antonyms": ["yield", "concede"]},
    "join": {"synonyms": ["connect", "unite", "merge", "combine"], "antonyms": ["separate", "divide", "leave"]},
    "separate": {"synonyms": ["divide", "split", "detach", "disconnect"], "antonyms": ["join", "combine", "unite"]},
    "judge": {"synonyms": ["evaluate", "assess", "determine", "appraise"], "antonyms": []},
    "know": {"synonyms": ["understand", "comprehend", "recognize", "realize"], "antonyms": ["ignore", "be ignorant"]},
    "laugh": {"synonyms": ["chuckle", "giggle", "grin", "cackle"], "antonyms": ["cry", "weep", "sob"]},
    "cry": {"synonyms": ["weep", "sob", "wail", "bawl"], "antonyms": ["laugh", "smile"]},
    "learn": {"synonyms": ["study", "acquire", "master", "grasp"], "antonyms": ["forget", "unlearn"]},
    "teach": {"synonyms": ["instruct", "educate", "train", "coach"], "antonyms": ["learn", "study"]},
    "limit": {"synonyms": ["restrict", "confine", "constrain", "cap"], "antonyms": ["expand", "extend", "liberate"]},
    "look": {"synonyms": ["see", "watch", "observe", "gaze", "glance"], "antonyms": ["ignore", "overlook"]},
    "make": {"synonyms": ["create", "produce", "build", "construct"], "antonyms": ["destroy", "break", "ruin"]},
    "manage": {"synonyms": ["handle", "oversee", "administer", "run"], "antonyms": ["neglect"]},
    "mean": {"synonyms": ["imply", "suggest", "indicate", "denote"], "antonyms": []},
    "measure": {"synonyms": ["gauge", "assess", "quantify", "evaluate"], "antonyms": []},
    "meet": {"synonyms": ["encounter", "greet", "come across"], "antonyms": ["avoid", "evade"]},
    "avoid": {"synonyms": ["evade", "dodge", "shun", "escape"], "antonyms": ["face", "confront", "meet"]},
    "move": {"synonyms": ["shift", "transfer", "relocate", "stir"], "antonyms": ["stay", "remain", "stop"]},
    "stay": {"synonyms": ["remain", "linger", "persist", "continue"], "antonyms": ["leave", "go", "move"]},
    "notice": {"synonyms": ["observe", "detect", "perceive", "spot"], "antonyms": ["ignore", "overlook", "miss"]},
    "offer": {"synonyms": ["present", "propose", "provide", "extend"], "antonyms": ["refuse", "withhold"]},
    "open": {"synonyms": ["unlock", "unfasten", "reveal", "launch"], "antonyms": ["close", "shut", "seal"]},
    "close": {"synonyms": ["shut", "seal", "lock", "fasten"], "antonyms": ["open", "unlock"]},
    "organize": {"synonyms": ["arrange", "coordinate", "structure", "plan"], "antonyms": ["disorganize", "disarrange"]},
    "own": {"synonyms": ["possess", "have", "hold", "maintain"], "antonyms": ["lack", "forfeit"]},
    "pay": {"synonyms": ["compensate", "reimburse", "settle", "fund"], "antonyms": ["receive", "earn"]},
    "perform": {"synonyms": ["execute", "carry out", "accomplish", "do"], "antonyms": ["neglect"]},
    "permit": {"synonyms": ["allow", "authorize", "let", "approve"], "antonyms": ["forbid", "prohibit", "ban"]},
    "persuade": {"synonyms": ["convince", "sway", "influence", "coax"], "antonyms": ["discourage", "dissuade"]},
    "place": {"synonyms": ["put", "set", "position", "lay"], "antonyms": ["remove", "take"]},
    "plan": {"synonyms": ["schedule", "arrange", "design", "prepare"], "antonyms": ["improvise"]},
    "play": {"synonyms": ["frolic", "engage", "perform", "compete"], "antonyms": ["work"]},
    "work": {"synonyms": ["labor", "toil", "operate", "function"], "antonyms": ["rest", "play", "idle"]},
    "praise": {"synonyms": ["commend", "compliment", "laud", "extol"], "antonyms": ["criticize", "blame", "condemn"]},
    "criticize": {"synonyms": ["critique", "censure", "blame", "condemn"], "antonyms": ["praise", "commend", "compliment"]},
    "prefer": {"synonyms": ["favor", "choose", "opt for", "lean toward"], "antonyms": ["reject", "dislike"]},
    "prepare": {"synonyms": ["ready", "arrange", "equip", "organize"], "antonyms": ["neglect"]},
    "prevent": {"synonyms": ["stop", "hinder", "block", "avert"], "antonyms": ["allow", "permit", "enable"]},
    "produce": {"synonyms": ["make", "create", "generate", "manufacture"], "antonyms": ["consume", "destroy"]},
    "protect": {"synonyms": ["defend", "guard", "shield", "safeguard"], "antonyms": ["attack", "endanger", "threaten"]},
    "prove": {"synonyms": ["demonstrate", "confirm", "verify", "establish"], "antonyms": ["disprove", "refute"]},
    "provide": {"synonyms": ["supply", "furnish", "offer", "deliver"], "antonyms": ["withhold", "deny"]},
    "publish": {"synonyms": ["release", "print", "issue", "broadcast"], "antonyms": ["suppress", "conceal"]},
    "pull": {"synonyms": ["tug", "drag", "draw", "haul"], "antonyms": ["push", "shove"]},
    "push": {"synonyms": ["shove", "thrust", "press", "propel"], "antonyms": ["pull", "tug"]},
    "raise": {"synonyms": ["lift", "elevate", "boost", "increase"], "antonyms": ["lower", "drop", "reduce"]},
    "lower": {"synonyms": ["drop", "reduce", "diminish", "decrease"], "antonyms": ["raise", "lift", "increase"]},
    "reach": {"synonyms": ["arrive at", "attain", "achieve", "contact"], "antonyms": []},
    "read": {"synonyms": ["peruse", "scan", "study", "review"], "antonyms": ["write"]},
    "write": {"synonyms": ["compose", "author", "draft", "pen"], "antonyms": ["read"]},
    "receive": {"synonyms": ["get", "obtain", "acquire", "accept"], "antonyms": ["give", "send", "donate"]},
    "give": {"synonyms": ["donate", "offer", "present", "grant"], "antonyms": ["receive", "take", "withhold"]},
    "recognize": {"synonyms": ["identify", "acknowledge", "know", "distinguish"], "antonyms": ["overlook", "ignore"]},
    "reduce": {"synonyms": ["decrease", "lessen", "diminish", "cut"], "antonyms": ["increase", "raise", "boost"]},
    "refuse": {"synonyms": ["decline", "reject", "deny", "turn down"], "antonyms": ["accept", "agree", "consent"]},
    "regret": {"synonyms": ["lament", "rue", "grieve", "mourn"], "antonyms": []},
    "relax": {"synonyms": ["unwind", "rest", "chill", "calm down"], "antonyms": ["tense", "stress", "work"]},
    "rely": {"synonyms": ["depend", "count on", "trust", "bank on"], "antonyms": ["distrust", "doubt"]},
    "remain": {"synonyms": ["stay", "continue", "persist", "endure"], "antonyms": ["leave", "go", "depart"]},
    "replace": {"synonyms": ["substitute", "swap", "exchange", "supersede"], "antonyms": ["keep", "retain"]},
    "represent": {"synonyms": ["symbolize", "stand for", "denote", "depict"], "antonyms": []},
    "request": {"synonyms": ["ask", "demand", "solicit", "appeal"], "antonyms": ["offer", "give"]},
    "require": {"synonyms": ["need", "demand", "necessitate", "call for"], "antonyms": []},
    "rescue": {"synonyms": ["save", "deliver", "free", "liberate"], "antonyms": ["abandon", "endanger"]},
    "abandon": {"synonyms": ["desert", "leave", "forsake", "quit"], "antonyms": ["keep", "retain", "rescue"]},
    "resist": {"synonyms": ["withstand", "oppose", "fight", "defy"], "antonyms": ["yield", "surrender", "submit"]},
    "respond": {"synonyms": ["reply", "answer", "react", "retort"], "antonyms": ["ignore"]},
    "restore": {"synonyms": ["repair", "renew", "revive", "recover"], "antonyms": ["damage", "destroy"]},
    "restrict": {"synonyms": ["limit", "confine", "constrain", "curb"], "antonyms": ["free", "liberate", "expand"]},
    "result": {"synonyms": ["outcome", "consequence", "effect"], "antonyms": ["cause"]},
    "return": {"synonyms": ["come back", "go back", "revert", "resume"], "antonyms": ["leave", "depart", "go"]},
    "rise": {"synonyms": ["ascend", "climb", "increase", "soar"], "antonyms": ["fall", "drop", "descend"]},
    "fall": {"synonyms": ["drop", "descend", "plunge", "tumble"], "antonyms": ["rise", "ascend", "climb"]},
    "save": {"synonyms": ["rescue", "conserve", "preserve", "protect"], "antonyms": ["spend", "waste", "squander"]},
    "spend": {"synonyms": ["expend", "use", "invest", "squander"], "antonyms": ["save", "conserve", "hoard"]},
    "search": {"synonyms": ["seek", "hunt", "look for", "explore"], "antonyms": ["find"]},
    "find": {"synonyms": ["discover", "locate", "uncover", "detect"], "antonyms": ["lose", "miss"]},
    "seem": {"synonyms": ["appear", "look", "sound", "feel"], "antonyms": []},
    "send": {"synonyms": ["dispatch", "transmit", "forward", "mail"], "antonyms": ["receive", "keep"]},
    "serve": {"synonyms": ["assist", "help", "attend", "provide"], "antonyms": []},
    "settle": {"synonyms": ["resolve", "decide", "conclude", "establish"], "antonyms": ["unsettle"]},
    "share": {"synonyms": ["distribute", "divide", "split", "allocate"], "antonyms": ["keep", "hoard"]},
    "show": {"synonyms": ["display", "demonstrate", "exhibit", "reveal"], "antonyms": ["hide", "conceal"]},
    "solve": {"synonyms": ["resolve", "figure out", "work out", "answer"], "antonyms": ["complicate"]},
    "speak": {"synonyms": ["talk", "say", "utter", "converse"], "antonyms": ["listen", "be silent"]},
    "listen": {"synonyms": ["hear", "attend", "heed", "pay attention"], "antonyms": ["ignore", "speak"]},
    "spend": {"synonyms": ["expend", "invest", "use up", "waste"], "antonyms": ["save", "conserve"]},
    "spread": {"synonyms": ["expand", "extend", "scatter", "distribute"], "antonyms": ["gather", "collect", "concentrate"]},
    "stand": {"synonyms": ["rise", "get up", "endure", "tolerate"], "antonyms": ["sit", "lie"]},
    "start": {"synonyms": ["begin", "commence", "launch", "initiate"], "antonyms": ["stop", "end", "finish"]},
    "suffer": {"synonyms": ["endure", "undergo", "experience", "bear"], "antonyms": ["enjoy", "thrive"]},
    "suggest": {"synonyms": ["propose", "recommend", "advise", "hint"], "antonyms": ["demand", "insist"]},
    "support": {"synonyms": ["help", "assist", "back", "endorse"], "antonyms": ["oppose", "undermine"]},
    "oppose": {"synonyms": ["resist", "challenge", "fight", "object"], "antonyms": ["support", "back", "endorse"]},
    "survive": {"synonyms": ["endure", "persist", "last", "outlast"], "antonyms": ["perish", "die"]},
    "tend": {"synonyms": ["lean", "incline", "trend", "gravitate"], "antonyms": []},
    "think": {"synonyms": ["ponder", "consider", "reflect", "contemplate"], "antonyms": []},
    "touch": {"synonyms": ["feel", "handle", "contact", "tap"], "antonyms": []},
    "translate": {"synonyms": ["interpret", "convert", "render", "decode"], "antonyms": []},
    "travel": {"synonyms": ["journey", "voyage", "tour", "wander"], "antonyms": ["stay"]},
    "treat": {"synonyms": ["handle", "manage", "regard", "attend to"], "antonyms": ["neglect", "ignore"]},
    "try": {"synonyms": ["attempt", "endeavor", "strive", "test"], "antonyms": []},
    "turn": {"synonyms": ["rotate", "spin", "revolve", "twist"], "antonyms": []},
    "understand": {"synonyms": ["comprehend", "grasp", "fathom", "realize"], "antonyms": ["misunderstand", "confuse"]},
    "use": {"synonyms": ["utilize", "employ", "apply", "leverage"], "antonyms": ["waste", "conserve"]},
    "visit": {"synonyms": ["call on", "attend", "tour", "go to"], "antonyms": []},
    "wait": {"synonyms": ["stay", "remain", "linger", "hold on"], "antonyms": ["rush", "hurry"]},
    "want": {"synonyms": ["desire", "wish", "crave", "need"], "antonyms": ["refuse", "reject"]},
    "warn": {"synonyms": ["caution", "alert", "notify", "advise"], "antonyms": []},
    "waste": {"synonyms": ["squander", "fritter", "drain", "deplete"], "antonyms": ["save", "conserve"]},
    "watch": {"synonyms": ["observe", "view", "monitor", "witness"], "antonyms": ["ignore", "neglect"]},
    "wear": {"synonyms": ["don", "sport", "carry", "bear"], "antonyms": ["remove", "doff"]},
    "win": {"synonyms": ["triumph", "succeed", "prevail", "conquer"], "antonyms": ["lose", "fail"]},
    "wish": {"synonyms": ["desire", "hope", "want", "yearn"], "antonyms": []},
    "wonder": {"synonyms": ["ponder", "question", "marvel", "speculate"], "antonyms": []},
    "worry": {"synonyms": ["fret", "stress", "anxiety", "concern"], "antonyms": ["relax"]},

    # ── 名词 ──
    "ability": {"synonyms": ["capability", "skill", "talent", "competence"], "antonyms": ["inability", "incapacity"]},
    "inability": {"synonyms": ["incapacity", "incompetence"], "antonyms": ["ability", "capability"]},
    "advantage": {"synonyms": ["benefit", "edge", "merit", "asset"], "antonyms": ["disadvantage", "drawback", "handicap"]},
    "disadvantage": {"synonyms": ["drawback", "handicap", "setback", "weakness"], "antonyms": ["advantage", "benefit", "merit"]},
    "answer": {"synonyms": ["reply", "response", "solution"], "antonyms": ["question", "query", "problem"]},
    "question": {"synonyms": ["query", "inquiry", "issue", "problem"], "antonyms": ["answer", "reply", "solution"]},
    "beauty": {"synonyms": ["elegance", "grace", "charm", "attractiveness"], "antonyms": ["ugliness"]},
    "ugliness": {"synonyms": ["hideousness"], "antonyms": ["beauty", "elegance"]},
    "beginning": {"synonyms": ["start", "origin", "commencement", "outset"], "antonyms": ["end", "finish", "conclusion"]},
    "end": {"synonyms": ["finish", "conclusion", "termination", "close"], "antonyms": ["beginning", "start", "origin"]},
    "belief": {"synonyms": ["faith", "trust", "conviction", "confidence"], "antonyms": ["doubt", "disbelief", "skepticism"]},
    "doubt": {"synonyms": ["uncertainty", "skepticism", "suspicion"], "antonyms": ["belief", "certainty", "confidence"]},
    "benefit": {"synonyms": ["advantage", "gain", "profit", "perk"], "antonyms": ["disadvantage", "drawback"]},
    "bravery": {"synonyms": ["courage", "valor", "heroism", "boldness"], "antonyms": ["cowardice", "fear", "timidity"]},
    "cowardice": {"synonyms": ["timidity", "fear", "weakness"], "antonyms": ["bravery", "courage", "valor"]},
    "calm": {"synonyms": ["peace", "serenity", "tranquility", "quiet"], "antonyms": ["chaos", "turmoil", "agitation"]},
    "chaos": {"synonyms": ["disorder", "turmoil", "confusion", "mayhem"], "antonyms": ["order", "calm", "peace"]},
    "chance": {"synonyms": ["opportunity", "possibility", "luck", "fortune"], "antonyms": []},
    "choice": {"synonyms": ["option", "selection", "alternative", "preference"], "antonyms": []},
    "confusion": {"synonyms": ["disorder", "chaos", "bewilderment", "perplexity"], "antonyms": ["clarity", "order"]},
    "courage": {"synonyms": ["bravery", "valor", "nerve", "boldness"], "antonyms": ["fear", "cowardice"]},
    "danger": {"synonyms": ["peril", "risk", "hazard", "threat"], "antonyms": ["safety", "security"]},
    "safety": {"synonyms": ["security", "protection", "shelter"], "antonyms": ["danger", "risk", "peril"]},
    "darkness": {"synonyms": ["gloom", "shadow", "blackness", "dimness"], "antonyms": ["light", "brightness"]},
    "light": {"synonyms": ["brightness", "illumination", "glow", "radiance"], "antonyms": ["darkness", "shadow"]},
    "death": {"synonyms": ["demise", "passing", "end", "expiration"], "antonyms": ["life", "birth"]},
    "life": {"synonyms": ["existence", "being", "living", "vitality"], "antonyms": ["death"]},
    "enemy": {"synonyms": ["foe", "opponent", "adversary", "rival"], "antonyms": ["friend", "ally"]},
    "friend": {"synonyms": ["ally", "companion", "buddy", "pal"], "antonyms": ["enemy", "foe"]},
    "failure": {"synonyms": ["defeat", "setback", "collapse", "fiasco"], "antonyms": ["success", "triumph"]},
    "success": {"synonyms": ["triumph", "achievement", "victory", "accomplishment"], "antonyms": ["failure", "defeat"]},
    "freedom": {"synonyms": ["liberty", "independence", "autonomy"], "antonyms": ["captivity", "slavery", "bondage"]},
    "captivity": {"synonyms": ["imprisonment", "slavery", "bondage"], "antonyms": ["freedom", "liberty"]},
    "happiness": {"synonyms": ["joy", "bliss", "contentment", "delight"], "antonyms": ["sadness", "misery", "sorrow"]},
    "sadness": {"synonyms": ["sorrow", "grief", "melancholy", "despair"], "antonyms": ["happiness", "joy", "bliss"]},
    "health": {"synonyms": ["wellness", "fitness", "well-being"], "antonyms": ["illness", "disease", "sickness"]},
    "illness": {"synonyms": ["disease", "sickness", "ailment", "malady"], "antonyms": ["health", "wellness"]},
    "knowledge": {"synonyms": ["wisdom", "understanding", "expertise", "learning"], "antonyms": ["ignorance", "inexperience"]},
    "ignorance": {"synonyms": ["stupidity", "unawareness", "naiety"], "antonyms": ["knowledge", "wisdom"]},
    "leader": {"synonyms": ["chief", "boss", "head", "director"], "antonyms": ["follower", "subordinate"]},
    "follower": {"synonyms": ["subordinate", "supporter", "disciple"], "antonyms": ["leader", "chief"]},
    "love": {"synonyms": ["affection", "devotion", "passion", "adoration"], "antonyms": ["hate", "hatred", "animosity"]},
    "hatred": {"synonyms": ["animosity", "hostility", "loathing", "enmity"], "antonyms": ["love", "affection"]},
    "noise": {"synonyms": ["sound", "racket", "din", "uproar"], "antonyms": ["silence", "quiet"]},
    "silence": {"synonyms": ["quiet", "hush", "stillness", "peace"], "antonyms": ["noise", "sound"]},
    "poverty": {"synonyms": ["destitution", "neediness", "hardship"], "antonyms": ["wealth", "prosperity"]},
    "wealth": {"synonyms": ["riches", "fortune", "prosperity", "affluence"], "antonyms": ["poverty", "destitution"]},
    "problem": {"synonyms": ["issue", "difficulty", "challenge", "trouble"], "antonyms": ["solution", "answer"]},
    "solution": {"synonyms": ["answer", "remedy", "resolution", "fix"], "antonyms": ["problem", "issue"]},
    "strength": {"synonyms": ["power", "force", "might", "vigor"], "antonyms": ["weakness", "frailty"]},
    "weakness": {"synonyms": ["frailty", "vulnerability", "flaw"], "antonyms": ["strength", "power"]},
    "truth": {"synonyms": ["fact", "reality", "verity", "certainty"], "antonyms": ["lie", "falsehood", "fiction"]},
    "lie": {"synonyms": ["falsehood", "fabrication", "untruth", "deception"], "antonyms": ["truth", "fact"]},
    "victory": {"synonyms": ["triumph", "win", "success", "conquest"], "antonyms": ["defeat", "loss", "failure"]},
    "defeat": {"synonyms": ["loss", "failure", "setback"], "antonyms": ["victory", "triumph", "win"]},
    "war": {"synonyms": ["conflict", "battle", "combat", "warfare"], "antonyms": ["peace", "truce"]},
    "peace": {"synonyms": ["harmony", "calm", "truce", "serenity"], "antonyms": ["war", "conflict"]},
    "youth": {"synonyms": ["adolescence", "teenager", "juvenile"], "antonyms": ["adult", "elder", "senior"]},

    # ── 副词 ──
    "always": {"synonyms": ["forever", "constantly", "continually", "perpetually"], "antonyms": ["never", "rarely"]},
    "never": {"synonyms": ["at no time", "not ever"], "antonyms": ["always", "constantly"]},
    "often": {"synonyms": ["frequently", "regularly", "commonly"], "antonyms": ["rarely", "seldom"]},
    "rarely": {"synonyms": ["seldom", "hardly", "infrequently"], "antonyms": ["often", "frequently"]},
    "quickly": {"synonyms": ["rapidly", "swiftly", "speedily", "promptly"], "antonyms": ["slowly", "gradually"]},
    "slowly": {"synonyms": ["gradually", "leisurely", "unhurriedly"], "antonyms": ["quickly", "rapidly"]},
    "easily": {"synonyms": ["effortlessly", "smoothly", "readily"], "antonyms": ["hardly", "difficultly"]},
    "carefully": {"synonyms": ["cautiously", "meticulously", "thoroughly"], "antonyms": ["carelessly", "recklessly"]},
    "carelessly": {"synonyms": ["recklessly", "negligently", "thoughtlessly"], "antonyms": ["carefully", "cautiously"]},
    "certainly": {"synonyms": ["definitely", "surely", "absolutely", "undoubtedly"], "antonyms": ["doubtfully", "uncertainly"]},
    "clearly": {"synonyms": ["obviously", "plainly", "evidently", "distinctly"], "antonyms": ["vaguely", "unclearly"]},
    "closely": {"synonyms": ["tightly", "intimately", "carefully"], "antonyms": ["loosely", "distantly"]},
    "eagerly": {"synonyms": ["enthusiastically", "keenly", "avidly"], "antonyms": ["reluctantly", "apathetically"]},
    "finally": {"synonyms": ["eventually", "ultimately", "at last"], "antonyms": ["initially"]},
    "fortunately": {"synonyms": ["luckily", "happily", "thankfully"], "antonyms": ["unfortunately"]},
    "unfortunately": {"synonyms": ["sadly", "regrettably", "unluckily"], "antonyms": ["fortunately", "luckily"]},
    "gently": {"synonyms": ["softly", "tenderly", "mildly", "delicately"], "antonyms": ["roughly", "harshly"]},
    "roughly": {"synonyms": ["harshly", "coarsely", "violently"], "antonyms": ["gently", "softly"]},
    "greatly": {"synonyms": ["enormously", "immensely", "vastly", "tremendously"], "antonyms": ["slightly", "barely"]},
    "hardly": {"synonyms": ["barely", "scarcely", "slightly"], "antonyms": ["easily", "readily"]},
    "honestly": {"synonyms": ["truthfully", "sincerely", "candidly"], "antonyms": ["dishonestly", "deceitfully"]},
    "immediately": {"synonyms": ["instantly", "promptly", "at once", "right away"], "antonyms": ["later", "eventually"]},
    "largely": {"synonyms": ["mainly", "mostly", "principally", "chiefly"], "antonyms": ["partly", "slightly"]},
    "merely": {"synonyms": ["only", "just", "simply", "barely"], "antonyms": []},
    "naturally": {"synonyms": ["normally", "obviously", "of course"], "antonyms": ["unnaturally"]},
    "nearly": {"synonyms": ["almost", "approximately", "close to"], "antonyms": ["completely"]},
    "normally": {"synonyms": ["usually", "typically", "generally"], "antonyms": ["abnormally", "unusually"]},
    "obviously": {"synonyms": ["clearly", "evidently", "plainly"], "antonyms": ["subtly"]},
    "perhaps": {"synonyms": ["maybe", "possibly", "conceivably"], "antonyms": ["certainly", "definitely"]},
    "politely": {"synonyms": ["courteously", "respectfully", "graciously"], "antonyms": ["rudely", "impolitely"]},
    "probably": {"synonyms": ["likely", "presumably", "perhaps"], "antonyms": ["unlikely"]},
    "recently": {"synonyms": ["lately", "currently", "of late"], "antonyms": []},
    "safely": {"synonyms": ["securely", "carefully", "harmlessly"], "antonyms": ["dangerously"]},
    "seriously": {"synonyms": ["gravely", "severely", "earnestly"], "antonyms": ["lightly", "casually"]},
    "simply": {"synonyms": ["merely", "just", "easily", "plainly"], "antonyms": ["complexly"]},
    "strongly": {"synonyms": ["firmly", "powerfully", "vigorously"], "antonyms": ["weakly", "feebly"]},
    "suddenly": {"synonyms": ["abruptly", "unexpectedly", "instantly"], "antonyms": ["gradually"]},
    "together": {"synonyms": ["jointly", "collectively", "unitedly"], "antonyms": ["apart", "separately"]},
    "usually": {"synonyms": ["normally", "typically", "generally", "commonly"], "antonyms": ["rarely", "seldom"]},
    "widely": {"synonyms": ["extensively", "broadly", "generally"], "antonyms": ["narrowly"]},
}


def get_synonyms(word: str) -> List[str]:
    """获取单词的近义词列表。

    Args:
        word: 要查询的英语单词

    Returns:
        近义词列表，如果没有则返回空列表
    """
    if not word:
        return []
    w = word.lower().strip()
    entry = _SYNONYM_ANTONYM_DB.get(w)
    if entry:
        return list(entry.get("synonyms", []))
    return []


def get_antonyms(word: str) -> List[str]:
    """获取单词的反义词列表。

    Args:
        word: 要查询的英语单词

    Returns:
        反义词列表，如果没有则返回空列表
    """
    if not word:
        return []
    w = word.lower().strip()
    entry = _SYNONYM_ANTONYM_DB.get(w)
    if entry:
        return list(entry.get("antonyms", []))
    return []


def get_related_words(word: str) -> Dict[str, List[str]]:
    """获取单词的近义词和反义词。

    Args:
        word: 要查询的英语单词

    Returns:
        dict with keys: synonyms, antonyms
    """
    return {
        "synonyms": get_synonyms(word),
        "antonyms": get_antonyms(word),
    }


def format_related_words(word: str) -> str:
    """格式化近义词/反义词为可读文本。

    Returns:
        例如: "近义词: glad, cheerful, joyful\n反义词: sad, unhappy, miserable"
        如果无数据则返回空字符串。
    """
    syns = get_synonyms(word)
    ants = get_antonyms(word)

    lines = []
    if syns:
        lines.append(f"近义词: {', '.join(syns)}")
    if ants:
        lines.append(f"反义词: {', '.join(ants)}")

    return "\n".join(lines)


def has_data(word: str) -> bool:
    """检查是否有该词的近义词/反义词数据。"""
    return word.lower().strip() in _SYNONYM_ANTONYM_DB
